name: '222'
'on':
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: {}
env:
  d: '21'
jobs:
  job-1:
    name: Job 1
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "Hello"
