name: '222'
'on':
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:
    inputs:
      opt:
        description: desm
        required: false
        type: choice
        options:
          - b
        default: b
env:
  d: '21'
jobs:
  job-1:
    name: Job 1
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo "Hello"
